#!/bin/bash
iacta file created by Amos Akwemoh in the working directory
Creating multiple lines so code can read third line
Third line created by Amos Akwemoh, hopefully the code reads this, inshallah
